version: '2'
services:
    qa:
        image: daocloud.io/quantaxis/qacommunity-rust-go:allin-20210218
        container_name: qacommunity-rust
        depends_on:
            - mgdb
            - qaeventmq
        networks:
            qanetwork:
                ipv4_address: 172.70.0.3
        ports:
            - "8888:8888"
            - "81:80"
            - "8787:8787"
        environment:
          - TZ=Asia/Shanghai
          - LANG=C.UTF-8
          - MONGODB=mgdb
          - QARUN=qaweb
          - QAPUBSUB_IP=qaeventmq
          - QAPUBSUB_PORT=5672
          - QAPUBSUB_USER=admin
          - QAPUBSUB_PWD=admin
        volumes:
            - qacode:/root/code
            #- /Volumes/DataDisk/19_data/QUANTAXIS/qacode:/data
        restart: unless-stopped


    qaweb:
        image: daocloud.io/quantaxis/qacommunity-rust-go:allin-20210218
        container_name: qaweb
        depends_on:
            - mgdb
            - qaeventmq
        networks:
            qanetwork:
                ipv4_address: 172.70.0.4
        ports:
            - "8010:8010"
            - "8018:8018"
            - "8019:8019"
            - "8028:8028"
            - "8029:8029"
        environment:
          - MONGODB=mgdb
          - QAPUBSUB_IP=qaeventmq
          - QAPUBSUB_PORT=5672
          - QAPUBSUB_USER=admin
          - QAPUBSUB_PWD=admin
          - QARUN_AMQP=pyamqp://admin:admin@qaeventmq:5672//
          - TZ=Asia/Shanghai
        restart: unless-stopped
        depends_on:
          - qaeventmq
          - mgdb
        command: ['/root/wait_for_it.sh', 'qaeventmq:5672', '--' , "/root/runcelery.sh"]


    # qacron:
    #     image: daocloud.io/quantaxis/qa-cron:latest
    #     environment:
    #         - MONGODB=mgdb
    #     restart: always


    mgdb:
        image: daocloud.io/quantaxis/qamongo_single:latest
        container_name: mgdb
        ports:
            - "27017:27017"
        environment:
            - TZ=Asia/Shanghai
            - MONGO_INITDB_DATABASE=quantaxis
        volumes:
            - qamg:/data/db
            #- /Volumes/DataDisk/19_data/QUANTAXIS/qamg/db:/data
        networks:
            qanetwork:
                ipv4_address: 172.70.0.2
        restart: unless-stopped


    qaeventmq:
        image: daocloud.io/quantaxis/qaeventmq:latest
        container_name: qaeventmq
        ports:
            - "15672:15672"
            - "5672:5672"
            - "4369:4369"
        environment:
            - TZ=Asia/Shanghai
        networks:
            qanetwork:
                ipv4_address: 172.70.0.5
        restart: unless-stopped


    qatrader:
        image: daocloud.io/quantaxis/qatrader:latest
        container_name: qatrader
        ports:
            - "8020:8020"
        depends_on:
            - mgdb
            - qaeventmq
        environment:
            - MONGODB=mgdb
            - QAPUBSUB_IP=qaeventmq
            - QAPUBSUB_PORT=5672
            - QAPUBSUB_USER=admin
            - QAPUBSUB_PWD=admin
            - QARUN_AMQP=pyamqp://admin:admin@qaeventmq:5672//
            - TZ=Asia/Shanghai
        command:
            ['/root/QATrader/docker/wait_for_it.sh', 'qaeventmq:5672', '--' ,'qatraderserver']
        restart: unless-stopped 
        networks:
            qanetwork:
                ipv4_address: 172.70.0.9


volumes:
    qamg:
        name: qamg
    qacode:
        name: qacode
networks:
    qanetwork:
        ipam:
            config:
            - subnet: 172.70.0.0/24
              gateway: 172.70.0.1