services:
    lucky:
        image: gdy666/lucky
        container_name: lucky
        network_mode: 'host'
        volumes:
            - '/volume2/docker/goodluck:/goodluck'
        restart: always
