version: '3.8'

services:
  # docker run --name zeebe -p 26500:26500 -p 9600:9600 camunda/zeebe:latest
  zeebe:
    image: camunda/zeebe:latest
    container_name: zeebe
    ports:
      - "26500:26500"
      - "9600:9600"
    environment:
      - ZEEBE_LOG_LEVEL=debug
  # docker run --name operate -p 8080:8080 --link zeebe camunda/operate:latest
  # Zeebe Operate（可选，用于监控）
  operate:
    image: camunda/operate:latest
    container_name: operate
    ports:
      - "8080:8080"
    environment:
      - CAMUNDA_OPERATE_ZEEBE_GATEWAY_ADDRESS=zeebe:26500
    depends_on:
      - zeebe