version: '3'
services:
  pandora-next:
    image: pengzhile/pandora-next
    container_name: PandoraNext
    network_mode: bridge
    restart: always
    ports:
      - "8181:8181"
    volumes:
      - ./data:/data
      - ./sessions:/root/.cache/PandoraNext
#docker pull pengzhile/pandora-next
#docker run -d --restart always --name PandoraNext --net=bridge \
#    -p 8181:8181 \
#    -v ./data:/data \
#    -v ./sessions:/root/.cache/PandoraNext \
#    pengzhile/pandora-next