version: '1.0'
services:
  # qinglong容器
  qinglong:
    image: whyour/qinglong:latest
    container_name: qinglong
    restart: unless-stopped
    tty: true
    ports:
      - 5700:5700
      - 5701:5701
    environment:
      - ENABLE_HANGUP=true
      - ENABLE_WEB_PANEL=true
    volumes:
      - ./config:/ql/config
      - ./log:/ql/log
      - ./db:/ql/db
      - ./repo:/ql/repo
      - ./raw:/ql/raw
      - ./scripts:/ql/scripts
      - ./jbot:/ql/jbot
      - ./ninja:/ql/ninja
    labels:
      - com.centurylinklabs.watchtower.enable=false
    #环境变量
    #environment:
      #- TZ=Asia/Shanghai
      #- LANG=en_US.UTF-8
# docker run -dit \
#   --name QL \
#   --hostname QL \
#   --restart always \
#   -p 5700:5700 \
#   -v $PWD/QL/config:/ql/config \
#   -v $PWD/QL/log:/ql/log \
#   -v $PWD/QL/db:/ql/db \
#   -v $PWD/QL/scripts:/ql/scripts \
#   -v $PWD/QL/jbot:/ql/jbot \
#   whyour/qinglong:latest
