version: '3.8'

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.12.1
    # 不要有下划线等特殊符号，win下会识别不了
    container_name: es712
    environment:
      - cluster.name=gann_es  #配置es集群名称
      - node.name=es7_01
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms2g -Xmx2g" #配置es启动参数
      - discovery.seed_hosts=es7_01
      #- "discovery.type=single-node" #配置es启动单节点
      - cluster.initial_master_nodes=es7_01 #,es7_02
      - path.data:F:\gann\elaticsearch\data
      - path.logs:F:\gann\elaticsearch\logs
      #- data01:/Users/dragon/program/elasticsearch/data
      # win 加上这些配置 es会检查你的环回网卡的配置
      - transport.host=localhost
      - transport.tcp.port=9300
      - http.port=9200
      - network.host=0.0.0.0
    ports:
      - "9200:9200"
      - "9300:9300"
    healthcheck:
      test: ["CMD-SHELL", "curl --silent --fail localhost:9200/_cluster/health || exit 1"]
      interval: 10s
      timeout: 10s
      retries: 3
    ulimits:
      memlock:
        soft: -1
        hard: -1
    networks:
      - elastic

  logstash:
    image: docker.elastic.co/logstash/logstash:7.12.1
    container_name: logstash712
    environment:
      - discovery.seed_hosts=logstash
      - "LS_JAVA_OPTS=-Xms512m -Xmx512m"
    volumes:
      # 配置文件
      - ./logstash/pipeline/logstash-nginx.config:/usr/share/logstash/pipeline/logstash-nginx.config
      # 日志文件
      - ./logstash/nginx.log:/home/nginx.log

    ports:
      - "5000:5000/tcp"
      - "5000:5000/udp"
      - "5044:5044"
      - "9600:9600"
    depends_on:
      - elasticsearch
    networks:
      - elastic
    command: logstash -f /usr/share/logstash/pipeline/logstash-nginx.config

  kibana:
    image: docker.elastic.co/kibana/kibana:7.12.1
    container_name: kibana712
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
    environment:
      - I18N_LOCALE=zh-CN
      - XPACK_GRAPH_ENABLED=true
      - TIMELION_ENABLED=true
      - XPACK_MONITORING_COLLECTION_ENABLED="true"
    networks:
      - elastic

networks:
  elastic:
    driver: bridge
