# Use root/example as user/password credentials
version: '3.1'
services:
  mongo:
    image: mongo
    container_name: mongodb
    # restart: always
    restart: 'no'
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 123456
    ports:
      - 27017:27017
    # 从 5.0 版开始 MongoDB 删除了--serviceExecutor命令行选项和相应的net.serviceExecutor配置选项。
    # command: "mongod --serviceExecutor adaptive"
    #定义挂载点
    volumes:
      #- ./config/mongodb.conf:/etc/config/mongodb.conf
      - ./data/db:/data/db
    networks:
      - mongodb
  mongo-express:
    image: mongo-express
    container_name: mongo-express
    restart: 'no'
    ports:
      # 修改管理界面的端口，要进去容器里面改文件：vi config.js port:  process.env.VCAP_APP_PORT  || mongo-express 跑起来以后䣌端口号，默认是8081，最好改一下
      - 27018:27018
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: 123456
      
      # ME_CONFIG_MONGODB_SERVER | 'mongo' | MongoDB container name. Use comma delimited list of host names for replica sets.
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_MONGODB_SERVER: mongodb
      
      # 可以使用连接 链接
      #ME_CONFIG_MONGODB_URL=mongodb://mongodb:27017

    networks:
      - mongodb

# 创建一个mongodb专用的网络
networks:
  mongodb:
    driver: bridge