# https://hub.docker.com/_/nginx
# docker run --name some-nginx -v /some/content:/usr/share/nginx/html:ro -d nginx
# docker run --name my-custom-nginx-container -v /host/path/nginx.conf:/etc/nginx/nginx.conf:ro -d nginx
# docker run -p 80:80 --name nginx --restart=always -v ./conf/nginx.conf:/etc/nginx/nginx.conf -v ./conf/conf.d:/etc/nginx/conf.d -v ./logs:/var/log/nginx -v ./html:/usr/share/nginx/html -d nginx

# nginx-docker-compose.yml ->   https://www.kancloud.cn/roeslys/linux/1690935
# 查看镜像漏洞摘要和建议→docker scout quickview nginx:latest
services:
  nginx:
    image: nginx:1.27.0
    volumes:
      - './html:/usr/share/nginx/html'
      - './logs:/var/log/nginx'
      - './conf/conf.d:/etc/nginx/conf.d'
      - './conf/nginx.conf:/etc/nginx/nginx.conf'
    restart: always
    container_name: nginx
    environment:
      - LANG=C.UTF-8
      - LC_ALL=C.UTF-8
    ports:
        - '80:80'
        - '443:443'
