# https://hub.docker.com/_/nginx
# docker run --name some-nginx -v /some/content:/usr/share/nginx/html:ro -d nginx
# docker run --name my-custom-nginx-container -v /host/path/nginx.conf:/etc/nginx/nginx.conf:ro -d nginx

# nginx-docker-compose.yml ->   https://www.kancloud.cn/roeslys/linux/1690935

version: '3'
services:
  nginx:
    image: nginx:latest
    container_name: nginx
    #network_mode: host
    volumes:
    - ./conf.d:/etc/nginx/conf.d
    - ./nginx.conf:/etc/nginx/nginx.conf
    - ./html:/usr/share/nginx/html
    - ./log:/var/log/nginx
    environment:
      - LANG=C.UTF-8
      - LC_ALL=C.UTF-8
    ports:
    - 8080:80
