# Use root/example as user/password credentials https://hub.docker.com/_/mariadb/
services:
  mariadb:
    image: mariadb:10.6
    container_name: mariadb
    ports:
      - "3306:3306"
    restart: always
    environment:
      #MYSQL_ROOT_PASSWORD: 123456
      # 将密码存放的容器位置
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/db-password
    # [Server] 'default_authentication_plugin' is deprecated and will be removed in a future release. Please use authentication_policy instead.
    #  [Warning] [MY-013360] [Server] Plugin mysql_native_password reported: ''mysql_native_password' is deprecated and will be removed in a future release. Please use caching_sha2_password instead'
    command: '--default_authentication_plugin=mysql_native_password'
    #SQLSTATE[HY000] [2054] The server requested authentication method unknown to the client
    #command: '--authentication_policy=caching_sha2_password'
    # 健康检查
    healthcheck:
      test: ['CMD-SHELL', 'mysqladmin ping -h 127.0.0.1 --password="$$(cat /run/secrets/db-password)" --silent']
      interval: 3s
      retries: 5
      start_period: 30s
    secrets:
      - db-password
    # 数据持久化
    volumes:
      - data:/var/lib/mysql
# 使用的密钥验证，用文件里的文本做密码
secrets:
  db-password:
    file: db/pwd.txt
  #adminer:
  #  image: adminer
  #  container_name: adminer
  #  restart: always
  #  ports:
  #    - 13306:8080
# docker-compose -f stack.yml up
# http://localhost:8080
# docker run --name mariadb -e MYSQL_ROOT_PASSWORD=123456 --network mynetwork --restart always -d -p 3306:3306 mariadb