# https://hub.docker.com/_/mysql
services:
  db:
    # 镜像和版本
    image: mysql:8.0.37
    # 容器名称
    container_name: mysql8
    restart: always
    environment:
      #MYSQL_ROOT_PASSWORD: 123456
      # 将密码存放的容器位置
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/db-password
    # [Server] 'default_authentication_plugin' is deprecated and will be removed in a future release. Please use authentication_policy instead.
    #  [Warning] [MY-013360] [Server] Plugin mysql_native_password reported: ''mysql_native_password' is deprecated and will be removed in a future release. Please use caching_sha2_password instead'
    command: '--authentication_policy=caching_sha2_password'  
    ports:
      - "23366:3306"
    # 健康检查
    healthcheck:
      test: ['CMD-SHELL', 'mysqladmin ping -h 127.0.0.1 --password="$$(cat /run/secrets/db-password)" --silent']
      interval: 3s
      retries: 5
      start_period: 30s
    secrets:
      - db-password
    # 数据持久化
    volumes:
      - data:/var/lib/mysql
# 使用的密钥验证，用文件里的文本做密码
secrets:
  db-password:
    file: db/pwd.txt