# https://hub.docker.com/_/postgres
# docker run -it --rm --network some-network postgres psql -h some-postgres -U postgres

# docker run -d \
# 	--name some-postgres \
# 	-e POSTGRES_PASSWORD=mysecretpassword \
# 	-e PGDATA=/var/lib/postgresql/data/pgdata \
# 	-v /custom/mount:/var/lib/postgresql/data \
# 	postgres

# Use postgres/example user/password credentials
version: '3.1'
services:
  db:
    image: postgres
    container_name: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: 123456
      PGDATA: ./data
    volumes:
      - ./data:/var/lib/postgresql/data