# https://hub.docker.com/_/postgres
# docker run -it --rm --network some-network postgres psql -h some-postgres -U postgres
# docker run --name some-postgres -e POSTGRES_PASSWORD=mysecretpassword -d postgres

# docker run -d \
# 	--name some-postgres \
# 	-e POSTGRES_PASSWORD=mysecretpassword \
# 	-e PGDATA=/var/lib/postgresql/data/pgdata \
# 	-v /custom/mount:/var/lib/postgresql/data \
# 	postgres

# Use postgres/example user/password credentials
version: '3.1'
services:
  postgresql:
    image: postgres:15.4-alpine
    container_name: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: "root"
      POSTGRES_PASSWORD: "123456"
      PGDATA: ./data
    volumes:
      - ./data:/var/lib/postgresql/data
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080