#https://hub.docker.com/_/redis
# redis://default:password@ip-address:6379
# docker exec -it redis /bin/bash
# redis-cli
# config set requirepass yourpassword
# config rewrite
# exit
services:
  #redis容器
  redis:
    #定义主机名
    #hostname: redis
    #使用的镜像
    image: redis:6.2.14
    container_name: redis
    #容器的映射端口
    ports:
      - 26399:6379
    restart: always
    #定义挂载点
    volumes:
      - ./redis.conf:/etc/redis/redis.conf
      - ./redis/data:/data
    #环境变量
    environment:
      - TZ=Asia/Shanghai
      - LANG=en_US.UTF-8
    #覆盖容器启动的redis.conf
    command: redis-server /etc/redis/redis.conf 
    # 用命令 加上密码；用配置文件 redis.conf requirepass 你的密码foobared
    # command: '--requirepass 你的redisPassword'

# docker run -it -p 6379:6379 --name redis --network=mynetwork \
# -v ./redis/redis.conf:/etc/redis/redis.conf \
# -v ./redis/data:/data \
# -d redis redis-server /etc/redis/redis.conf \
# --appendonly yes --requirepass "123456"